language: cpp

compiler:
  - g++
  - clang

os: linux

dist: bionic

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - libboost1.70-dev
      - valgrind
      - gdb
env:
  - CXXSTANDARD=17

after_failure:
  - COREFILE=$(find $TRAVIS_BUILD_DIR/cores -maxdepth 1 -name "core.*" -print | head -1)
  - echo $COREFILE
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" $EXEC -ex "thread apply all bt" -ex "set pagination 0" -batch; fi

before_script:
  - ulimit -c
  - ulimit -a -S
  - ulimit -a -H
  - mkdir -p -m 0777 $TRAVIS_BUILD_DIR/cores
  - sudo sysctl -w kernel.core_pattern=$TRAVIS_BUILD_DIR/cores/core.%e.%p
  - cat /proc/sys/kernel/core_pattern
  - git clone https://github.com/google/googletest.git
  - cd googletest && cmake -DCMAKE_INSTALL_PREFIX=install .
  - make install
  - cd ..

script:
  - ulimit -c unlimited -S #enable core dumps
  - >
    cmake
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -DCMAKE-BUILD_TYPE=RelWithDebInfo
    -DCMAKE_INSTALL_PREFIX=tests
    -DCMAKE_CXX_FLAGS_INIT='-Wall -Wextra -m64 -ftemplate-backtrace-limit=0 -faligned-new -O3'
    -DCMAKE_CXX_STANDARD=$CXXSTANDARD
    -DGTEST_ROOT=googletest/install .
    -DQUANTUM_ENABLE_TESTS=ON
    -DQUANTUM_BOOST_USE_VALGRIND=ON
  - make QuantumTests && ./tests/QuantumTests.Linux64
